import java.util.Properties;

/**
 * Generates a default gradle-wrapper.properties to standard out.
 */
public class GenerateWrapperProperties {
    public static void main(String[] args) throws Exception {
        Properties properties = new Properties();
        properties.put("distributionBase", "GRADLE_USER_HOME");
        properties.put("distributionPath", "wrapper/dists");
        properties.put("zipStoreBase", "GRADLE_USER_HOME");
        properties.put("distributionUrl", System.getProperty("distributionUrl"));
        properties.store(System.out, "Generated by GNG");
    }
}
